<a href="https://colab.research.google.com/github/mamuncseru/deep_understanding_deep_learning/blob/main/DUDL_math_matrixMult.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#import libraries
import numpy as np
import torch

# Using numpy

In [7]:
# create some random matrices
A = np.random.randn(3, 4)
B = np.random.randn(4, 5)
C = np.random.randn(3, 7)

# try some multiplications ...
print(np.round( A@B, 2)), print(' ')
# print(np.round( A@C, 2)), print(' ')
# print(np.round( B@C, 2)), print(' ')
print(np.round( C.T@A, 2))

[[ 0.69  1.71  2.97  0.96 -0.87]
 [-0.43  1.16  3.25 -1.38  2.09]
 [-1.32 -0.75  1.02  1.5  -2.2 ]]
 
[[-0.69  1.22 -1.22 -2.01]
 [-0.88 -0.15 -0.84  2.23]
 [ 0.29 -1.65  2.2  -0.04]
 [-1.64  0.45 -1.35  0.41]
 [-1.29  2.17 -3.19 -0.23]
 [ 0.25 -0.29  0.53 -0.24]
 [-2.29  2.1  -3.62  0.15]]


# Using Pytorch

In [13]:
# create some random matrices
A = torch.randn(3, 4)
B = torch.randn(4, 5)
C1 = np.random.randn(4, 7)
C2 = torch.tensor(C1, dtype=torch.float )

# try some multiplications ...
print(np.round( A@B, 2)), print(' ')
# print(np.round( A@B.T, 2)), print(' ')
print(np.round( A@C1, 2)), print(' ')
print(np.round( A@C2, 2))

tensor([[-0.5700,  1.2800,  0.9400,  0.5400, -1.4100],
        [ 1.1500,  2.1400,  1.4700,  0.2400,  0.7200],
        [-4.8100, -0.8900,  0.4100,  3.9400,  0.2900]])
 
tensor([[-0.4500, -1.5300, -2.0600,  4.7500, -0.1500,  1.7300, -3.8000],
        [ 2.4800,  2.3100,  1.2200, -2.8700, -0.7400, -0.1500,  2.2800],
        [ 2.8100,  2.4600,  1.3400, -0.7600,  1.6700, -5.6500,  0.0700]],
       dtype=torch.float64)
 
tensor([[-0.4500, -1.5300, -2.0600,  4.7500, -0.1500,  1.7300, -3.8000],
        [ 2.4800,  2.3100,  1.2200, -2.8700, -0.7400, -0.1500,  2.2800],
        [ 2.8100,  2.4600,  1.3400, -0.7600,  1.6700, -5.6500,  0.0700]])
