<a href="https://colab.research.google.com/github/mamuncseru/deep_understanding_deep_learning/blob/main/DUDL_math_randomseed.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# import libaries
import numpy as np
import torch


In [5]:
# generate a few random numbers
np.random.randn(5)

array([ 2.171257  ,  1.15231025, -1.81881234, -0.13804934,  0.53983961])

In [8]:
# repeat after fixing the seed (old-but-still-widely-used method)
np.random.seed(17)
print(np.random.randn(5))
print(np.random.randn(5))

# [ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
# [ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]

[ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
[ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]


## New seed mechanism in numpy

In [13]:
randseed1 = np.random.RandomState(17)
randseed2 = np.random.RandomState(20210530)

print(randseed1.randn(5)) # same sequence
print(randseed2.randn(5)) # different from above, but same each time
print(randseed1.randn(5)) # same as two up
print(randseed2.randn(5)) # same as two up
print(np.random.randn(5)) # different every time

# [ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
# [-0.24972681 -1.01951826  2.23461339  0.72764703  1.2921122 ]
# [ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]
# [ 1.15494929 -0.0015467  -0.11196868 -1.08136725  0.10265891]
# [ 0.44122749 -0.33087015  2.43077119 -0.25209213  0.10960984]

[ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
[-0.24972681 -1.01951826  2.23461339  0.72764703  1.2921122 ]
[ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]
[ 1.15494929 -0.0015467  -0.11196868 -1.08136725  0.10265891]
[-1.19276461 -0.20487651 -0.35882895  0.6034716  -1.66478853]


## Using pytorch

In [15]:
torch.randn(5)

tensor([-1.4012,  0.9051,  0.3183, -1.5953, -0.2892])

In [18]:
torch.manual_seed(17)
print(torch.randn(5))

# torch's seed doesn't spread to numpy
print(np.random.randn(5))

tensor([-1.4135,  0.2336,  0.0340,  0.3499, -0.0145])
[-0.98060789 -0.85685315 -0.87187918 -0.42250793  0.99643983]
