<a href="https://colab.research.google.com/github/mamuncseru/deep_understanding_deep_learning/blob/main/DUDL_math_argmin.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# import libraries
import numpy as np
import torch
import torch.nn as nn

### Using Numpy

In [2]:
# create a vector
v = np.array([1, 40, 2, -3])

# find and report the maximum and minimum values
minval = np.min(v)
maxval = np.max(v)

print("Min, max: %g, %g" %(minval, maxval))

Min, max: -3, 40


In [4]:
# now for the argmin/max
minidx = np.argmin(v)
maxidx = np.argmax(v)

print('Min, Max indices: %g, %g' %(minidx, maxidx) ), print(' ')

# confirm
print(f"Min val is {v[minidx] }, max val is { v[maxidx] }")

Min, Max indices: 3, 1
 
Min val is -3, max val is 40


In [5]:
# repeat with matrix
M = np.array([ [0, 1, 10], [20, 8, 5] ])
print(M), print(' ')

# various minima in this matrix!
minvals1 = np.min(M) # minimum from entire matrix
minvals2= np.min(M, axis=0) # minimum of each column (across rows)
minvals3 = np.min(M, axis=1) # minimum of each row (across columns)

# print them out
print(minvals1)
print(minvals2)
print(minvals3)


[[ 0  1 10]
 [20  8  5]]
 
0
[0 1 5]
[0 5]


In [6]:
# various minima in this matrix!
minidx1 = np.argmin(M)  # minimum from entire matrix
minidx2 = np.argmin(M, axis=0) # minimum of each column (across rows)
minidx3 = np.argmin(M, axis=1) # minimum of each row (across columns)

# print them out
print(M), print(' ') # reminder
print(minidx1)
print(minidx2)
print(minidx3)

[[ 0  1 10]
 [20  8  5]]
 
0
[0 0 1]
[0 2]


### Using pytorch

In [7]:
# create a vector
v = torch.tensor([1, 40, 2, -3])

# find and report the maximum and minimum values
minval = torch.min(v)
maxval = torch.max(v)

print("Min, max: %g, %g" %(minval, maxval))

Min, max: -3, 40


In [8]:
# now for the argmin/max
minidx = torch.argmin(v)
maxidx = torch.argmax(v)

print('Min, Max indices: %g, %g' %(minidx, maxidx) ), print(' ')

# confirm
print(f"Min val is {v[minidx] }, max val is { v[maxidx] }")

Min, Max indices: 3, 1
 
Min val is -3, max val is 40


In [9]:
# repeat with matrix
M = torch.tensor([ [0, 1, 10], [20, 8, 5] ])
print(M), print(' ')

# various minima in this matrix!
minvals1 = torch.min(M) # minimum from entire matrix
minvals2= torch.min(M, axis=0) # minimum of each column (across rows)
minvals3 = torch.min(M, axis=1) # minimum of each row (across columns)

# print them out
print(minvals1)
print(minvals2)
print(minvals3)


tensor([[ 0,  1, 10],
        [20,  8,  5]])
 
tensor(0)
torch.return_types.min(
values=tensor([0, 1, 5]),
indices=tensor([0, 0, 1]))
torch.return_types.min(
values=tensor([0, 5]),
indices=tensor([0, 2]))


In [10]:
# various minima in this matrix!
minidx1 = torch.argmin(M)  # minimum from entire matrix
minidx2 = torch.argmin(M, axis=0) # minimum of each column (across rows)
minidx3 = torch.argmin(M, axis=1) # minimum of each row (across columns)

# print them out
print(M), print(' ') # reminder
print(minidx1)
print(minidx2)
print(minidx3)

tensor([[ 0,  1, 10],
        [20,  8,  5]])
 
tensor(0)
tensor([0, 0, 1])
tensor([0, 2])


In [11]:
minvals2.values

tensor([0, 1, 5])

In [12]:
minvals2.indices

tensor([0, 0, 1])