<a href="https://colab.research.google.com/github/mamuncseru/deep_understanding_deep_learning/blob/main/DUDL_regularization_dropout.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# imports
import numpy as np
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
import torch.nn.functional as F
from sklearn.model_selection import train_test_split

## Using dropout

In [11]:
# define a dropout instance and make some data
prob = .5

dropout = nn.Dropout(p = prob)
x = torch.ones(10)

# let's see what dropout returns
y = dropout(x)
print(x)
print(y*(1-prob))
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([0., 1., 0., 0., 1., 1., 1., 1., 1., 0.])
tensor(1.2000)


In [12]:
# dropout is turned off when evaluating the model
dropout.eval()
y = dropout(x)
print(y)
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor(1.)


In [13]:
# annoyingly, F.dropout() is not deactivated in eval mode:

dropout.eval()
y = F.dropout(x)
print(y)
print(torch.mean(y))

tensor([2., 2., 0., 0., 2., 2., 0., 2., 0., 2.])
tensor(1.2000)


In [15]:
# but you can manually switch it off
# dropout.eval()
y = F.dropout(x, training=False)

print(y)
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor(1.)


In [18]:
# the model needs to be reset after toggling into eval mode
dropout.train()
y = dropout(x)
print(y)

dropout.eval()
y = dropout(x)
print(y)

dropout.train()
y= dropout(x)
print(y)

tensor([2., 2., 2., 0., 2., 2., 0., 2., 0., 0.])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([2., 2., 2., 2., 0., 0., 0., 0., 2., 0.])
