<a href="https://colab.research.google.com/github/mamuncseru/deep_understanding_deep_learning/blob/main/DUDL_overfitting_trainDevsetTest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#import libraries
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
## create fake dataset
fakedata = np.tile(np.array([1, 2, 3, 4]), (10, 1)) + np.tile(10*np.arange(1, 11), (4, 1)).T
fakelabels = np.arange(10) > 4
print(fakedata), print(' ')
print(fakelabels)

[[ 11  12  13  14]
 [ 21  22  23  24]
 [ 31  32  33  34]
 [ 41  42  43  44]
 [ 51  52  53  54]
 [ 61  62  63  64]
 [ 71  72  73  74]
 [ 81  82  83  84]
 [ 91  92  93  94]
 [101 102 103 104]]
 
[False False False False False  True  True  True  True  True]


## Using train_test_split

In [6]:
# specify sizes of the partitions
# oder is train, devset, test
partitions = [.8, .1, .1]

# split the data (not ethe third input, and the TMP in the variable name)
train_data, testTMP_data, train_labels, testTMP_labels = \
            train_test_split(fakedata, fakelabels, train_size=partitions[0])

# now split the TMP data
split = partitions[1] / np.sum(partitions[1:])
devset_data, test_data, devset_labels, test_labels = \
    train_test_split(testTMP_data, testTMP_labels, train_size=split)

# print out the sizes
print('Training data size: ' + str(train_data.shape))
print('TestTMP data size: ' + str(testTMP_data.shape))
print('Devset data size: ' + str(devset_data.shape))
print('Test data size: ' + str(test_data.shape))
print(' ')

# print out the train/test data
print('Training data: ')
print(train_data)

print('Devset data: ')
print(devset_data)

print('Test data: ')
print(test_data)

Training data size: (8, 4)
TestTMP data size: (2, 4)
Devset data size: (1, 4)
Test data size: (1, 4)
 
Training data: 
[[ 51  52  53  54]
 [ 11  12  13  14]
 [ 31  32  33  34]
 [ 21  22  23  24]
 [101 102 103 104]
 [ 41  42  43  44]
 [ 61  62  63  64]
 [ 91  92  93  94]]
Devset data: 
[[81 82 83 84]]
Test data: 
[[71 72 73 74]]


# splitting the data manually using numpy

In [9]:
# partition sizes in proportion
partitions = np.array([.8, .1, .1])
print('Partition proportions:')
print(partitions)
print(' ')

# convert those into integers
partitionBnd = np.cumsum(partitions * len(fakelabels)).astype(int)
print('Partition boundaries:')
print(partitionBnd)
print(' ')

# random indices
randindices = np.random.permutation(range(len(fakelabels)))
print('Randomized data indices:')
print(randindices)
print(' ')

Partition proportions:
[0.8 0.1 0.1]
 
Partition boundaries:
[ 8  9 10]
 
Randomized data indices:
[2 9 8 0 3 6 7 1 5 4]
 


In [10]:
# select rows for the training data
train_dataN = fakedata[randindices[:partitionBnd[0]], :]
train_labelsN = fakedata[randindices[:partitionBnd[0]]]

# select rows for the deveset data
devset_dataN = fakedata[randindices[partitionBnd[0]:partitionBnd[1]], :]
devset_labelsN = fakelabels[randindices[partitionBnd[0]:partitionBnd[1]]]

# select rows for the testset data
test_dataN = fakedata[randindices[partitionBnd[1]:], :]
test_labelsN = fakelabels[randindices[partitionBnd[1]:]]

In [11]:
train_dataN

array([[ 31,  32,  33,  34],
       [101, 102, 103, 104],
       [ 91,  92,  93,  94],
       [ 11,  12,  13,  14],
       [ 41,  42,  43,  44],
       [ 71,  72,  73,  74],
       [ 81,  82,  83,  84],
       [ 21,  22,  23,  24]])

In [14]:
devset_dataN

array([[61, 62, 63, 64]])

In [15]:
test_dataN

array([[51, 52, 53, 54]])