<a href="https://colab.research.google.com/github/mamuncseru/deep_understanding_deep_learning/blob/main/DUDL_math_matrixMult.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#import libraries
import numpy as np
import torch

# Using numpy

In [3]:
# create some random matrices
A = np.random.randn(3, 4)
B = np.random.randn(4, 5)
C = np.random.randn(3, 7)

# try some multiplications ...
print(np.round( A@B, 2)), print(' ')
# print(np.round( A@C, 2)), print(' ')
# print(np.round( B@C, 2)), print(' ')
# print(np.round( C.T@A, 2))

[[-3.49  1.81 -1.73  1.12  1.97]
 [-0.67 -3.34 -1.56 -2.12  0.37]
 [-2.47  0.21 -2.04 -0.    0.77]]
 


(None, None)